### ISSUE TITLE
chef-percona trying to install 5.6 when 5.5 is defined

### ISSUE THREAD

**Issue by asciifaceman** [sous-chefs/percona#329] opened 2015-07-27 19:18 UTC
On the first run, 5.5 is installed as defined by the attribute default["percona"]["version"] = "5.5". On every chef-client run afterwards it tries to upgrade it to 5.6: (sorry for the open text markdown isn't working for some reason)

Running handlers:
[2015-07-27T19:08:57+00:00] ERROR: Running exception handlers
   Chef::Handler::SlackReporting
Running handlers complete
[2015-07-27T19:08:57+00:00] ERROR: Exception handlers complete
[2015-07-27T19:08:57+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 26 resources updated in 15.738233345 seconds
[2015-07-27T19:08:58+00:00] ERROR: mysql2_chef_gem[default](tfly-onsale-management-service-db::install line 28) had an error: Mixlib::ShellOut::ShellCommandFailed: package[percona-server-client-5.6](percona::client line 9) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of apt-get -q -y install percona-server-client-5.6=5.6.25-73.1-1.precise ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  libaio1 libmysqlclient18 libdbd-mysql-perl percona-server-common-5.5
  libperconaserverclient18
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  percona-server-client-5.5 percona-server-server-5.5
The following NEW packages will be installed:
  percona-server-client-5.6
0 upgraded, 1 newly installed, 2 to remove and 106 not upgraded.
Need to get 0 B/10.1 MB of archives.
After this operation, 75.7 MB disk space will be freed.
(Reading database ... 72136 files and directories currently installed.)
Removing percona-server-server-5.5 ...
Removing percona-server-client-5.5 ...
Processing triggers for man-db ...
STDERR: \* Stopping MySQL (Percona Server) mysqld
   ...fail!
invoke-rc.d: initscript mysql, action "stop" failed.
dpkg: error processing percona-server-server-5.5 (--remove):
 subprocess installed pre-removal script returned error exit status 1
- Stopping MySQL (Percona Server) mysqld
  ...fail!
  invoke-rc.d: initscript mysql, action "stop" failed.
- Percona Server is distributed with several useful UDF (User Defined Function) from Percona Toolkit.
- Run the following commands to create these functions:
  
  mysql -e "CREATE FUNCTION fnv1a_64 RETURNS INTEGER SONAME 'libfnv1a_udf.so'"
  mysql -e "CREATE FUNCTION fnv_64 RETURNS INTEGER SONAME 'libfnv_udf.so'"
  mysql -e "CREATE FUNCTION murmur_hash RETURNS INTEGER SONAME 'libmurmur_udf.so'"
- See http://www.percona.com/doc/percona-server/5.5/management/udf_percona_toolkit.html for more details
- Starting MySQL (Percona Server) database server mysqld
  ...done.
  dpkg: percona-server-client-5.5: dependency problems, but removing anyway as you requested:
  percona-server-server-5.5 depends on percona-server-client-5.5 (>= 1:5.5.44-rel37.3-1.precise).
  Errors were encountered while processing:
  percona-server-server-5.5
  E: Sub-process /usr/bin/dpkg returned an error code (1)
  ---- End output of apt-get -q -y install percona-server-client-5.6=5.6.25-73.1-1.precise ----
  Ran apt-get -q -y install percona-server-client-5.6=5.6.25-73.1-1.precise returned 100
  [2015-07-27T19:08:58+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

This is on Ubuntu 12.04 on AWS. It ran perfectly fine every time in Kitchen, so I don't understand this behavior.

**Comment by epcim** [comment] 2015-11-19 16:07
any idea?

**Comment by asciifaceman** [comment] 2015-11-19 19:50
I want to comment that this issue was from a previous company I no longer work for, so I would mostly be unable to verify any fixes since it took so long to investigate.

**Comment by jamesooo** [comment] 2016-11-01 00:49
I can confirm that this issue is still present.

Recipe: percona::package_repo
         * yum_repository[percona] action create
           * template[/etc/yum.repos.d/percona.repo] action create
             - create new file /etc/yum.repos.d/percona.repo
             - update content in file /etc/yum.repos.d/percona.repo from none to 0aae73
             --- /etc/yum.repos.d/percona.repo	2016-11-01 00:43:50.615518696 +0000
             +++ /etc/yum.repos.d/.chef-percona20161101-128-19i035g.repo	2016-11-01 00:43:50.615518696 +0000
             @@ -1 +1,11 @@
             +# This file was generated by Chef
             +# Do NOT modify this file by hand.
             +
             +[percona]
             +name=Percona Packages
             +baseurl=http://repo.percona.com/centos/6/os/x86_64/
             +enabled=1
             +gpgcheck=1
             +gpgkey=http://www.percona.com/downloads/RPM-GPG-KEY-percona
             +sslverify=true
             - change mode from '' to '0644'
           * execute[yum clean metadata percona] action run
             - execute yum clean metadata --disablerepo=* --enablerepo=percona
           * execute[yum-makecache-percona] action run
             - execute yum -q -y makecache --disablerepo=* --enablerepo=percona
           * ruby_block[yum-cache-reload-percona] action create
             - execute the ruby block yum-cache-reload-percona
           * execute[yum clean metadata percona] action nothing (skipped due to action :nothing)
           * execute[yum-makecache-percona] action nothing (skipped due to action :nothing)
           * ruby_block[yum-cache-reload-percona] action nothing (skipped due to action :nothing)

       Recipe: percona::server
         * yum_package[mysql-libs] action remove (up to date)
       Recipe: percona::client
         * yum_package[Percona-Server-devel-56] action install
           - install version 5.6.33-rel79.0.el6 of package Percona-Server-devel-56
         * yum_package[Percona-Server-client-56] action install
           - install version 5.6.33-rel79.0.el6 of package Percona-Server-client-56
       Recipe: percona::server
         * yum_package[Percona-Server-server-55] action install

           ================================================================================
           Error executing action `install` on resource 'yum_package[Percona-Server-server-55]'
           ================================================================================

           Chef::Exceptions::Exec
           ----------------------
           yum -d0 -e0 -y install Percona-Server-server-55-5.5.52-rel38.3.el6 returned 1:
           STDOUT:  You could try using --skip-broken to work around the problem
            You could try running: rpm -Va --nofiles --nodigest

           STDERR: Error: Percona-Server-client-56 conflicts with Percona-Server-client-55-5.5.52-rel38.3.el6.x86_64

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/percona/recipes/server.rb

            32:   package node["percona"]["server"]["package"] do
            33:     action node["percona"]["server"]["package_action"].to_sym
            34:   end
            35: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/percona/recipes/server.rb:32:in `from_file'

           yum_package("Percona-Server-server-55") do
             package_name "Percona-Server-server-55"
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :package
             cookbook_name "percona"
             recipe_name "server"
             flush_cache {:before=>false, :after=>false}
           end

           Platform:
           ---------
           x86_64-linux

       Recipe: ppi_rhel::apache
         * httpd_service_rhel_sysvinit[apache] action restart
           * service[httpd-apache] action restart
             - restart service service[httpd-apache]


       Running handlers:
       [2016-11-01T00:44:26+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-11-01T00:44:26+00:00] ERROR: Exception handlers complete
       Chef Client failed. 73 resources updated in 48 seconds
       [2016-11-01T00:44:26+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-11-01T00:44:26+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-11-01T00:44:26+00:00] ERROR: yum_package[Percona-Server-server-55] (percona::server line 32) had an error: Chef::Exceptions::Exec: yum -d0 -e0 -y install Percona-Server-server-55-5.5.52-rel38.3.el6 returned 1:
       STDOUT:  You could try using --skip-broken to work around the problem
        You could try running: rpm -Va --nofiles --nodigest

       STDERR: Error: Percona-Server-client-56 conflicts with Percona-Server-client-55-5.5.52-rel38.3.el6.x86_64

       [2016-11-01T00:44:26+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-centos-6>.  Please see .kitchen/logs/default-centos-6.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

i'm happy to confirm any fixes put in place

**Comment by jamesooo** [comment] 2016-11-01 01:57
i did a little bit of digging here and i think the issue lies in accessing node["percona"]["version"] inside of attributes/client.rb
it looks like the node values used in here are only aware of values specified inside the cookbook and cannot be overridden by the calling cookbook. it'll probably be best to move the following
```ruby
case node["platform_family"]
when "debian"
  abi_version = case version
                when "5.5" then "18"
                when "5.6" then "18.1"
                else ""
                end

  if Array(node["percona"]["server"]["role"]).include?("cluster")
    default["percona"]["client"]["packages"] = %W[
      libperconaserverclient#{abi_version}-dev percona-xtradb-cluster-client-#{version}
    ]
  else
    default["percona"]["client"]["packages"] = %W[
      libperconaserverclient#{abi_version}-dev percona-server-client-#{version}
    ]
  end
when "rhel"
  if Array(node["percona"]["server"]["role"]).include?("cluster")
    default["percona"]["client"]["packages"] = %W[
      Percona-XtraDB-Cluster-devel-#{version} Percona-XtraDB-Cluster-client-#{version}
    ]
  else
    default["percona"]["client"]["packages"] = %W[
      Percona-Server-devel-#{version} Percona-Server-client-#{version}
    ]
  end
end
```
into a recipe. i'm going to try my hand at this but i'm still pretty new to chef so no promises i'll be able to get this quickly.

**Comment by jamesooo** [comment] 2016-11-01 03:41
I've got a fix on my repo but it looks like i'm not authorized to submit a pull request here. can someone add me?
my commit:
https://github.com/jamesooo/chef-percona/commit/898d178c9bfcb5e3c70de8f7359f5dc5f150f4eb

**Comment by xblitz** [comment] 2017-02-10 20:49
I also have a problem of this being in the attributes file, not about the version but about the Cluster/Standalone version of the client. will this be merged?

**Comment by jamesooo** [comment] 2017-02-10 21:09
Not sure if it'll get merged in. I've been waiting for this to be accepted for a while. Looks like the tests also need to be updated. I think this repo might not be getting worked on. Feel free to clone my fork and work from that tho.

**Comment by xblitz** [comment] 2017-02-10 21:11
there is an issue about transferring the repo to other maintainers... #362

**Comment by Xorima** [comment] 2019-05-11 17:13
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

**Closed by Xorima** 2019-05-11 17:13 UTC
